# Generated by Django 5.0.2 on 2024-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
